version: "3.8"

services:
  nginx:
    image: nginx:1.24.0-bullseye
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/nginx/certificates:/etc/letsencrypt
    depends_on:
      - app
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=tommy
      - POSTGRES_PASSWORD=aBiqp1K28l
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
  app:
    build:
      context: .
      target: production
    image: secure-ryman-app:latest
    expose:
      - 3000
    volumes:
      - .:/app:consistent
      - app-node_modules:/app/node_modules
    depends_on:
      - postgres

volumes:
  postgres:
  app-node_modules:
